#!/bin/bash
json=0

while getopts ":j" arg; do
    case $arg in
        j)
            json=1
            ;;
    esac
done

if [[ json == 1 ]]; then
    if pgrep -x redshift &> /dev/null; then
        echo '{"icon":"lightbulb","state":"Good", "text": " ON"}'
    else
        echo '{"icon":"lightbulb","state":"Idle", "text": "OFF"}'
    fi
else
    if pgrep -x redshift &> /dev/null; then
        echo " ON"
    else
        echo "OFF"
    fi
fi
