#!/bin/bash
source $HOME/.local/lib/prompt-yn

handle_sigint () {
    echo "Received SIGINT(Ctrl+C)..."
    exit 0
}

trap handle_sigint SIGINT

if promptyn "Install packages?"; then
    $HOME/.dotfiles/fedora.packages
fi

if promptyn "Configure system?"; then
    $HOME/.dotfiles/fedora.configure
fi
