#!/bin/bash
promptyn () {
    while true; do
        read -p "$1 [Y/n] " yn
        case $yn in
            [Yy]*) return 0;;
            [Nn]*) return 1;;
            ""*) return 0;;
            *) continue;;
        esac
    done
}

promptny () {
    while true; do
        read -p "$1 [y/N] " yn
        case $yn in
            [Yy]*) return 0;;
            [Nn]*) return 1;;
            ""*) return 0;;
            *) continue;;
        esac
    done
}

handle_sigint () {
    echo "Received SIGINT(Ctrl+C)..."
    exit 0
}

trap handle_sigint SIGINT

if promptyn "Install packages?"; then
    $HOME/.dotfiles/fedora.packages
fi

if promptyn "Configure system?"; then
    $HOME/.dotfiles/fedora.configure
fi
